# Generated by Django 5.2.11 on 2026-02-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_user_type_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
