# Generated by ChatGPT - create AccountOpening model
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_completion_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_openings', to='api.user')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_openings', to='api.lead')),
            ],
            options={
                'ordering': ['-created_at'],
                'app_label': 'api',
            },
        ),
    ]
