# Generated by Django 5.2.11 on 2026-02-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_accountopening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('not_interested', 'Not Interested'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
